### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by JbPons** [tiaanduplessis/formik-error-focus#22]
Hi,
I try to use the library with typescript. So basically, i add a declare module with the type from Scroll To Element. 
Finally, i have something works. I think the type can be better but i don't have time to inspect further...

So, if it's possible, it would be better to implement typescript support.

````typescript
declare module 'formik-error-focus' {
    interface Options {
        offset: number;
        align?: 'top' | 'middle' | 'bottom';
        ease?: string;
        duration?: number;
        focusDelay?: number;
    }

    export default function FormikErrorFocus(props: Options);
}

**Comment by tiaanduplessis** [comment]
Updated in v2.0.0
